### ISSUE TITLE
Implement filesystem structure

### ISSUE THREAD

**Issue by pythontrade** [davidecaruso/shell.js#13]
Hi David, thanks for the great project! Is there any way to implement some kind of function to handle `cd` commands? If one of the commands requests a change of directory, then ideally this would update the path of the emulator in the main window and the title bar. 

Or perhaps even simpler: in the commands argument, accept a key:value pair of something like:

commands = {
  ['input': 'cd mydir'],
  ['input':'ls', 'output', 'subdir1 subdir2', 'path': '~/mydir/']
}

adding 'path' as an optional parameter for each command allows the user to override the path being displayed for each command, and makes it not necessary to keep track of the filesystem by any other means.

**Comment by davidecaruso** [comment]
Hi, with the newest release I introduced a way to make command-as-a-function. Documentation is not aligned yet, but you can find an example of implementation in the source code: `/src/assets/index.html`.

I'm gonna to mark as resolved.
