### ISSUE TITLE
Scrollbars, max window height

### ISSUE THREAD

**Issue by pythontrade** [davidecaruso/shell.js#14]
Currently, (depending on screen viewport width - especially on a narrow mobile) the shell.js window height may not be sufficiently large initially to contain all the commands that will be displayed by shell.js. 

Hence, as typed.js continues filling the screen, this may cause in the window height shifting towards the end of the commands. Cumulative layout shift would then present an issue with google pagerank. Adding scrollbars could fix this issue. Is it possible to have a max-window-height with scrollbar options, or perhaps to define a min-window-height (and no scrollbars)?

shell__content css specification currently are given as 

`.shell__content {\n  font-family: monospace; }\n\n.shell {\n  font-weight: 400; }\n\n.shell {\n  width: 400px;\n  height: 300px;\n  display: -webkit-box;\n  display: **-ms-flexbox;\n  display: flex;\n  -ms-flex-wrap: wrap;\n**      flex-wrap: wrap;\n  -webkit-box-orient: vertical;\n  -webkit-box-direction: normal;\n      -ms-flex-direction: column;\n          flex-direction: column;\n  position: relative;\n  text-align: left;\n  color: #F1F1F1;\n  **overflow: hidden**;\n  font-weight: 300;\n  -webkit-box-shadow: 0 5px 20px 0 rgba(0, 0, 0, 0.5);\n 
`

Flexbox will cause the size of the box to increase as needed - this is not best practice for inclusion on a webpage though, as it will negatively impact google pagerank if layout shift occurs. 

Perhaps a modification can be made to 
* remove flexbox specification
* add overflow-y: scroll

**Comment by davidecaruso** [comment]
Hi, with the newest release I probably fixed this issue. I'm gonna to mark as resolved, otherwise feel free to open a pull request.
