### ISSUE TITLE
Title should be in the center of free space

### ISSUE THREAD

**Issue by jcubic** [davidecaruso/shell.js#2]
Title is in the center of the window and I think it should be in the center of free space so not including the buttons because when window is small (width 250 + windows 10 + "C:\windows\" title)

You can see this in this demo https://codepen.io/jcubic/pen/WZvYGj just edit the resizable width and then change type to windows and resize the window.

**Comment by jcubic** [comment]
To fix this you need to set the `right` property of the title to width of the buttons.

**Comment by jcubic** [comment]
I've fix this by applying:
```css
.shell.windows .status-bar .title {
    right: 106px;
}
```

**Comment by davidecaruso** [comment]
Unfortunately you are using a previous version of the library that I will no longer support. Please use the new version instead or fix as you can.
