### ISSUE TITLE
Can i use it with user input?

### ISSUE THREAD

**Issue by li-nd** [davidecaruso/shell.js#35]
Hi! Can i use it with user input?

For example i want to create few commands and give an ability to user type it with keyboard, but now i can't understand how to do it, because according to Docs all i can to do - this is invoke type(['command']) so user can't type it directly in terminal?
Thanks.

**Comment by davidecaruso** [comment]
Hi @VSKut,
the library does not support this kind of feature, it works only with a list of predefined commands – as the `type` method expects.
If you'd like to have this feature you are free to open a pull request.
