### ISSUE TITLE
Js Callback

### ISSUE THREAD

**Issue by xRealNeon** [davidecaruso/shell.js#7]
Is there a function where you can get a callback when a certain command is executed?
EDIT: Add a function to use the console as a normal console

**Comment by davidecaruso** [comment]
No, there is no callback function after a command was executed, substantially because commands are sequential outputted strings, so please describe a use-case where a callback function could be useful.

And, what do you mean with _Add a function to use the console as a normal console_?

**Comment by xRealNeon** [comment]
I mean if you can implement the function that you can type commands and get a callback.

**Comment by davidecaruso** [comment]
Sorry but it is not much clear. If you mean making shell interactive – just like a text input – it is not what this library actually do, but I am open to accept pull request, indeed I invite you to contribute introducing new features like this.

**Comment by xRealNeon** [comment]
Yeah, I might do it later but at the time I have no time for it😉
